version: 2

sources:
  - name: migration
    schema: dbo
    tables:
      - name: Alert
      - name: Courier
      - name: Customer
      - name: ImportPackage
      - name: Invoice
      - name: InvoiceDetail
      - name: InvoiceDiscount
      - name: OtherCharge
      - name: PackagePackageEvent
      - name: Payment
      - name: PreAlert
      - name: SignUp
      - name: Supplier
      - name: User
      - name: alert_standalone_migrate
      - name: customer_standalone_migrate
      - name: invoicemaster_key_migrate
      - name: invoicedetails_migrate
      - name: payment_migrate
      - name: othercharge_migrate
      - name: package_key_migrate
      - name: packageevent_migrate
      - name: packagestatus_migrate
      - name: prealert_standalone_migrate
      - name: signups_standalone_migrate
